# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-30 03:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mutation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_position', models.IntegerField(default=0, verbose_name='Start Position')),
                ('end_position', models.IntegerField(default=0, verbose_name='End Position')),
                ('mutation', models.CharField(max_length=200, verbose_name='Mutation')),
                ('mutation_annotation', models.CharField(max_length=2000, verbose_name='Mutation Annotation')),
                ('gene_name', models.CharField(max_length=200, verbose_name='Gene Name')),
                ('gene_product', models.CharField(max_length=2000, verbose_name='Gene Product')),
            ],
        ),
    ]
