# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-30 05:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LTEE_Ecoli', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mutation',
            name='clone',
            field=models.CharField(default='', max_length=20, verbose_name='Clone'),
        ),
        migrations.AddField(
            model_name='mutation',
            name='generation',
            field=models.IntegerField(default=-1, verbose_name='Generation'),
        ),
        migrations.AddField(
            model_name='mutation',
            name='population',
            field=models.CharField(default='', max_length=20, verbose_name='Population'),
        ),
        migrations.AlterField(
            model_name='mutation',
            name='end_position',
            field=models.IntegerField(default=-1, verbose_name='End Position'),
        ),
        migrations.AlterField(
            model_name='mutation',
            name='gene_name',
            field=models.CharField(default='', max_length=200, verbose_name='Gene Name'),
        ),
        migrations.AlterField(
            model_name='mutation',
            name='gene_product',
            field=models.CharField(default='', max_length=2000, verbose_name='Gene Product'),
        ),
        migrations.AlterField(
            model_name='mutation',
            name='mutation',
            field=models.CharField(default='', max_length=200, verbose_name='Mutation'),
        ),
        migrations.AlterField(
            model_name='mutation',
            name='mutation_annotation',
            field=models.CharField(default='', max_length=2000, verbose_name='Mutation Annotation'),
        ),
        migrations.AlterField(
            model_name='mutation',
            name='start_position',
            field=models.IntegerField(default=-1, verbose_name='Start Position'),
        ),
    ]
